schema:
  - './src/temp/GraphQLIntrospectionResult.json'
documents: '**/*.graphql'
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
cacheDir: __generated__
config:
    reactApolloVersion: 2
    useIndexSignature: true
