schema:
  - './src/temp/GraphQLIntrospectionResult.json'
documents: 'src/**/*.graphql'
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
cacheDir: .generated
config:
    reactApolloVersion: 2
    useIndexSignature: true
