import {
  GraphQLSiteInfoService,
  SitecoreNextjsConfig,
  SiteInfo,
} from '@sitecore-jss/sitecore-jss-nextjs';
import fs from 'fs';
import { createGraphQLClientFactory } from 'lib/graphql-client-factory/create';
import path from 'path';

generateSites();

function generateSites(): void {
  console.log('Fetching site information');
  const config = {
    client: {
      xmcloud: {
        sitecoreEdgeContextId: process.env.SITECORE_EDGE_CONTEXT_ID || '123',
        sitecoreEdgeUrl: process.env.SITECORE_EDGE_URL,
      },
    },
  };
  const siteInfoService = new GraphQLSiteInfoService({
    clientFactory: createGraphQLClientFactory(config as SitecoreNextjsConfig),
  });
  siteInfoService
    .fetchSiteInfo()
    .then((sites) => {
      writeSites(sites);
    })
    .catch((e) => {
      console.error('Error generating sites file');
      console.error(e);
      process.exit(1);
    });
}

function writeSites(sites: SiteInfo[]): void {
  let configText = `/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.
const sites = ${JSON.stringify(sites)}\n`;

  configText += `module.exports = sites;`;

  const configPath = path.resolve('src/temp/sites.js');
  console.log(`Writing runtime config to ${configPath}`);
  fs.writeFileSync(configPath, configText, { encoding: 'utf8' });
}
