compressionLevel: mixed

enableGlobalCache: false

enableInlineBuilds: false

logFilters:
  - code: YN0061
    level: discard
  - code: YN0032
    level: discard
  - code: YN0013
    level: discard
  - code: YN0060
    level: discard
  - code: YN0002
    level: discard
  - code: YN0076
    level: discard
  - code: YN0007
    level: discard

nmHoistingLimits: workspaces

nmSelfReferences: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.4.1.cjs
