/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-builder/index.ts to modify the generation of this file.

import * as TestComponent from '../components/TestComponent';
import { Component1 } from 'src/components/TestComponent2';
import { Component2 } from 'src/components/TestComponent2';

export const components = new Map();
components.set('TestComponent', TestComponent);
components.set('Component1', Component1);
components.set('Component2', Component2);

// export const componentBuilder = new ComponentBuilder({ components });

// export const moduleFactory = componentBuilder.getModuleFactory();
