/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-factory.js to modify the generation of this file.
import ContentBlock from './ContentBlock.jsx';
import ReactGraphqlIntegratedDemo from './GraphQL-IntegratedDemo.jsx';
import ReactGraphqlLayout from './GraphQL-Layout.jsx';

const components = new Map();
components.set('React-ContentBlock', ContentBlock);
components.set('React-GraphQL-IntegratedDemo', ReactGraphqlIntegratedDemo);
components.set('React-GraphQL-Layout', ReactGraphqlLayout);

export default function componentFactory(componentName) {
  return components.get(componentName);
};
