/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-builder/index.ts to modify the generation of this file.

import * as TestComponentNonStandard from '../components/TestComponent';

export const components = new Map();
components.set('TestComponentNonStandard', TestComponentNonStandard);

// export const componentBuilder = new ComponentBuilder({ components });

// export const moduleFactory = componentBuilder.getModuleFactory();
