name: 'Docs Request for an Update or Improvement'
description: A request to update or improve JSS documentation. Alternatively you can send a feedback about the documentation to docsite@sitecore.net
labels: ['📑 doc']
body:
  - type: textarea
    attributes:
      label: What is the improvement or update you wish to see?
      description: 'Example: I would like to see example of how to use the `<Text>` component. Or, the `<Text>` component docs are missing information.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is there any context that might help us understand?
      description: Please add any other context that might help us understand.
    validations:
      required: true
  - type: input
    attributes:
      label: Does the docs page already exist? Please link to it.
    validations:
      required: false
