import { ComponentFile } from '../../utils';

/**
 * Generates an auto-generated file that exports all components in the project.
 * @param {ComponentFile[]} components The components to export
 * @param {string} project The project name
 * @returns The generated file as a string
 */
export const generateProjectComponents = (components: ComponentFile[], project: string): string => {
  return `/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/component-factory/startComponentFactoryCreator.ts to modify the generation of this file.
${components
  .map(
    (c) =>
      `export * as ${c.componentName} from 'src/projects/${project}/components/${c.componentName}';`
  )
  .join('\n')}
`;
};
