import { ComponentFile } from './component-factory';

export const generateProjectComponents = (components: ComponentFile[]): string => {
  return `/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-factory.ts to modify the generation of this file.
${components.map((c) => `export * as ${c.componentName} from './${c.componentName}';`).join('\n')}
`;
};
