import { ComponentFile } from './models';

/**
 * Generates an auto-generated file that exports all components in the project.
 * @param components The components to export
 * @param project The project name
 * @returns The generated file as a string
 */
export const generateProjectComponents = (components: ComponentFile[], project: string): string => {
  return `/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-factory-creator.ts to modify the generation of this file.
${components
  .map(
    c =>
      `export * as ${c.componentName} from 'src/projects/${project}/components/${c.componentName}';`
  )
  .join('\n')}
`;
};
