/* tslint:disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.
export const environment = {
  "production": false,
  "sitecoreApiHost": "https://sc.dev.local",
  "sitecoreApiKey": "{6A3CA915-CF47-4243-A932-9925207EE9CA}",
};
