name: Node.js CI

on:
  push:
    branches:
      - master
      - dev
      - 'release/*'
  pull_request:
    branches:
      - master
      - dev
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      lernaSinceFlag: "--since=origin/dev"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Clean Yarn cache and install dependencies
        run: |
          yarn cache clean --all
          yarn install --immutable

      - name: Lint packages
        run: |
          yarn lint-packages ${{ env.lernaSinceFlag }}

      - name: Build packages
        run: |
          npm run build

      - name: Run tests
        run: |
          yarn coverage-packages
        env:
          testEnv: 'ci'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Scaffold samples
        run: |
          yarn scaffold-samples
        if: always() && env.shouldPublish != 'true'

      - name: Refresh Yarn install
        run: |
          yarn install
        if: always() && env.shouldPublish != 'true'
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: Lint samples
        run: |
          yarn lint-samples ${{ env.lernaSinceFlag }}
        if: always() && env.shouldPublish != 'true'
