# runs npm shrinkwrap on packages on PRs to dev
# TODO: only run when a dependency changes in a package instead of every PR
name: auto-shrinkwrapper
# Controls when the action will run. 
on:
  # Triggers the workflow on PR to dev branch
  pull_request:
    branches:
      - dev
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "shrinkwrap"
  shrinkwrap:
    name: shrinkwrap pacakges
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      # the command should loop through each package and shrinkwrap the package-lock.json file if it exits
      # this is so JSS developer don't need to remember to shrinkwrap manual after updating dependencies.
      - name: shrinkwrap packages
        working-directory: ./packages
        run: for i in ./**/; do echo running npm shrinkwrap in $i; cd $i; npm shrinkwrap; cd ..; done;
      # end shrinkwrap job
      # This job should add the shrinkwrap files and commit them
      - name: commit changes
        # documentation for this action here: https://github.com/marketplace/actions/add-commit
        uses: EndBug/add-and-commit@v7.2.0
        with:
          # default author message
          default_author: github_actions
          # default message
          message: 'ran npm shrinkwrap for each package'
          cwd: './'
