# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  pull_request:
    branches:
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "shrinkwrap"
  shrinkwrap:
    name: shrinkwrap pacakges
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      # the command should loop through each package and shrinkwrap the package-lock.json file if it exits
      # this is so JSS developer don't need to remember to shrinkwrap manual after updating dependencies.
      - name: shrinkwrap packages
        working-directory: ./jss/packages
        run: for i in ./**/; do echo $i; cd $i; npm shrinkwrap; cd ..; done;
